### ISSUE TITLE
please solve this issue, I am unable to dump in csv file in python

### ISSUE THREAD

**Issue by 23BCA284** [vtcbca/internal-exam-23BCA284#2]
![Screenshot (10)](https://github.com/user-attachments/assets/a790445b-2231-431c-8fbf-1bcc416a12cd)
![Screenshot (11)](https://github.com/user-attachments/assets/0d51d937-af38-43ed-95a7-4e8edabbbd83)
![Screenshot (12)](https://github.com/user-attachments/assets/456d9b06-afc9-45fe-802d-4cce19e5faf0)

**Comment by amitvtcbb** [comment]
HERE YOU HAVE TO CREATE CSV FILE USING READER OBJECT.

**Comment by 23BCA284** [comment]
Thank you sir for giving suggestion of csv file .
through reader object error is solve.
